好的，让我先进行一次口腔检查，看看您的牙齿状况如何。在检查过程中，我会询问您的牙齿症状和历史，并观察您的牙齿和牙龈。

从您的描述中，您可能患有牙本质过敏。这是一种常见的问题，通常由于牙釉质磨损、龋齿或牙龈退缩等原因引起。当暴露在冷、热或甜食物时，可能会引起剧烈的疼痛。

为了解决这个问题，我建议您使用含氟牙膏来加强釉质，并使用专门针对敏感牙齿的漱口水。此外，请避免食用过于冷或过于热的食物和饮料，并尝试减少吃甜食。

如果您的情况比较严重，我们可以考虑进行一些治疗措施，例如涂抹氟化物、填充或根管治疗等。

最后，请记得定期进行口腔检查和清洁，并遵循正确的刷牙和使用牙线方法来保持良好的口腔卫生。

Daily quota: 9/10
ENG | ES | عربي | 中文 | فارسی
